"""Offline card ability and related-token catalog.

The compact JSON is generated by ``scripts/update_card_effect_data.py`` from
the official card-library endpoint.  This module is deliberately independent
from the deck-name CSV so effects and token relations can be consumed by
training tools without changing the existing deck editor.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
import sys

from .card_catalog import canonical_card_id


@dataclass(frozen=True)
class CardEffect:
    card_id: int
    base_card_id: int
    name: str
    skill_text: str
    evo_skill_text: str
    card_type: int
    class_id: int
    cost: int
    is_token: bool
    related_card_ids: tuple[int, ...]
    specific_effect_card_ids: tuple[int, ...]


def _sources() -> tuple[Path, ...]:
    package_root = Path(__file__).resolve().parent
    runtime_root = Path(getattr(sys, "_MEIPASS", package_root.parent))
    executable_root = Path(sys.executable).resolve().parent
    return (
        runtime_root / "shadowverse_tracker" / "data" / "card_effects_chs.json",
        executable_root / "_internal" / "shadowverse_tracker" / "data" / "card_effects_chs.json",
        package_root / "data" / "card_effects_chs.json",
    )


@lru_cache(maxsize=1)
def load_card_effects() -> dict[int, CardEffect]:
    source = next((path for path in _sources() if path.is_file()), None)
    if source is None:
        return {}
    try:
        payload = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    raw_cards = payload.get("cards") if isinstance(payload, dict) else None
    if not isinstance(raw_cards, dict):
        return {}
    result: dict[int, CardEffect] = {}
    for raw_id, raw in raw_cards.items():
        if not isinstance(raw, dict):
            continue
        try:
            card_id = int(raw.get("card_id", raw_id))
            result[card_id] = CardEffect(
                card_id=card_id,
                base_card_id=int(raw.get("base_card_id") or card_id),
                name=str(raw.get("name") or ""),
                skill_text=str(raw.get("skill_text") or ""),
                evo_skill_text=str(raw.get("evo_skill_text") or ""),
                card_type=int(raw.get("type") or 0),
                class_id=int(raw.get("class_id") or 0),
                cost=int(raw.get("cost") or 0),
                is_token=bool(raw.get("is_token")),
                related_card_ids=tuple(int(value) for value in raw.get("related_card_ids", ())),
                specific_effect_card_ids=tuple(
                    int(value) for value in raw.get("specific_effect_card_ids", ())
                ),
            )
        except (TypeError, ValueError):
            continue
    return result


def get_card_effect(card_id: int) -> CardEffect | None:
    value = int(card_id)
    effects = load_card_effects()
    return effects.get(value) or effects.get(canonical_card_id(value))


def related_token_ids(card_id: int) -> tuple[int, ...]:
    """Return token IDs explicitly related to a card in the source data."""
    effect = get_card_effect(card_id)
    if effect is None:
        return ()
    effects = load_card_effects()
    values = effect.related_card_ids + effect.specific_effect_card_ids
    return tuple(value for value in values if effects.get(value) and effects[value].is_token)


_TAG_RE = re.compile(r"<[^>]+>")
_CARD_HAND_RE = re.compile(r"(?:将|增加|添加|加入)\s*\d*\s*张?.{0,16}(?:到|加入).{0,8}手牌")
_SPELL_DRAW_RE = re.compile(r"抽(?:取)?\s*\d*\s*张?\s*(?:法术|咒语)")
_FOLLOWER_DRAW_RE = re.compile(r"抽(?:取)?\s*\d*\s*张?\s*(?:随从|从者)")
_MAGIC_BOOST_RE = re.compile(r"发动\s*(\d*)\s*次魔力增幅")


def is_spell(card_id: int) -> bool:
    effect = get_card_effect(card_id)
    # The WB API uses type 4 for spells (type 2 is an amulet-like card).
    # Keeping this mapping here avoids treating cards such as 智慧光辉 as
    # non-spells when calculating Wizard's spell-play boosts.
    return effect is not None and effect.card_type == 4


def magic_boost_amount(card_id: int, trigger: str) -> int:
    effect = get_card_effect(card_id)
    if effect is None:
        return 0
    text = _TAG_RE.sub("", effect.skill_text)
    desired = ("谢幕曲", "谢幕") if trigger == "destroy" else ("入场曲", "登场曲")
    # Evolution sections are also not part of an ordinary play trigger.
    other = (("入场曲", "登场曲", "进化时", "超进化时") if trigger == "destroy" else
             ("谢幕曲", "谢幕", "进化时", "超进化时"))
    matches = list(_MAGIC_BOOST_RE.finditer(text))
    total = 0
    for match in matches:
        # Effects often contain both entry and last-words sections.  Attribute
        # the activation to the keyword immediately preceding the phrase.
        last_desired = max((text.rfind(word, 0, match.start()) for word in desired), default=-1)
        last_other = max((text.rfind(word, 0, match.start()) for word in other), default=-1)
        # Some spells state the effect directly, without an 入场曲/谢幕曲
        # section (for example 和睦欢聚). Those effects happen on play and
        # must also be counted. When sections are present, attribute the
        # phrase only to the requested trigger to avoid double counting an
        # entry and evolution/last-words copy of the same text.
        if last_desired < 0 and last_other < 0:
            total += int(match.group(1) or 1)
        elif last_desired > last_other:
            total += int(match.group(1) or 1)
    return total


def inferred_hand_additions(card_id: int, trigger: str) -> tuple[tuple[object, int], ...]:
    """Infer only explicit card/type additions from a card's effect text.

    This is intentionally conservative: it requires the official relation
    list for exact Tokens and does not infer a card identity from a generic
    draw.  The returned tuples use the same format as ``KNOWN_HAND_EFFECTS``.
    """
    effect = get_card_effect(card_id)
    if effect is None:
        return ()
    text = _TAG_RE.sub("", effect.skill_text or "")
    trigger_words = ("谢幕曲", "谢幕") if trigger == "destroy" else ("入场曲", "登场曲")
    if not any(word in text for word in trigger_words):
        return ()
    additions: list[tuple[object, int]] = []
    if _SPELL_DRAW_RE.search(text):
        additions.append(("unknown_spell", 1))
    if _FOLLOWER_DRAW_RE.search(text):
        additions.append(("unknown_follower", 1))
    if _CARD_HAND_RE.search(text):
        for token_id in related_token_ids(card_id):
            token = load_card_effects().get(token_id)
            if token and token.name and token.name in text:
                amount_match = re.search(
                    rf"(?:将|增加|添加|加入)\s*(\d+)?\s*张?[^。；\n]{{0,24}}{re.escape(token.name)}",
                    text,
                )
                amount = int(amount_match.group(1) or 1) if amount_match else 1
                additions.append((token_id, amount))
    return tuple(additions)


__all__ = [
    "CardEffect",
    "get_card_effect",
    "inferred_hand_additions",
    "is_spell",
    "load_card_effects",
    "magic_boost_amount",
    "related_token_ids",
]
